config/routes.rb
Rails.application.routes.draw do
  resources :password_resets

  namespace :admin do
  get 'dashboard/index'
  end

  get 'sessions/new'

  resources :products, only: [:index, :show]

  root "static_pages#home"

  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  get 'logout' => "sessions#destroy"
  get 'home' => "static_pages#home"
  get 'about' => "static_pages#about"
  get 'contact' => "static_pages#contact"

  get 'search' => "products#search"

  namespace :admin do
    get '' => "dashboard#index", as: '/'
    resources :products
    resources :users
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	enum status: %w(featured newer normal)

	has_many :pictures, dependent: :destroy
	accepts_nested_attributes_for :pictures, 
																reject_if: proc { |attributes| attributes['image'].blank? },
																allow_destroy: true

	validates_presence_of :name, :description

	before_validation :default_status

	before_save :default_cover

	def default_status
		self.status = :normal if status.blank?
	end

	def default_cover
		self.pictures.build if self.pictures.blank?
	end

	def self.search(search)
		@search = search.downcase
		if search
			where('lower(name) LIKE ? OR lower(description) LIKE ?', "%#{@search}%", "%#{@search}%")
		else
			all
		end
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, except: [:show]
  after_action :verify_authorized

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    authorize @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    authorize @product
  end

  # GET /products/new
  def new
    @product = Product.new
    authorize @product
    3.times do
      @product.pictures.build
    end
  end

  # GET /products/1/edit
  def edit
    authorize @product
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    authorize @product
    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize @product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize @product
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @products = Product.search(params[:query])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :status, pictures_attributes: [:image])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, except: [:index, :show, :search]
  after_action :verify_authorized, except: [:search]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    authorize @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    authorize @product
  end

  # GET /products/new
  def new
    @product = Product.new
    authorize @product
    3.times do
      @product.pictures.build
    end
  end

  # GET /products/1/edit
  def edit
    authorize @product
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    authorize @product
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize @product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize @product
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @products = Product.search(params[:query])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, pictures_attributes: [:image])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product], html: {class: 'inner-form', multipart: true}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>This form contains <%= pluralize(@product.errors.count, "error") %> </h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, Product.statuses.collect {|k, v| [k.humanize, k]}, {},class: 'form-control' %>
  </div>
  <%= f.fields_for :pictures do |builder| %>
    <%= builder.label :image, "Picture" %>
    <%= builder.file_field :image, class:'btn btn-info btn-file' %>   
  <% end %>
  <div class="actions">
    <%= f.submit submit_text, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing product</h1>
		<%= render 'form', submit_text: "Save Changes" %>
		<%= link_to 'Show', admin_product_path(@product), class: 'btn btn-default' %> |
		<%= link_to 'Back', admin_products_path, class: 'btn btn-default' %>
	</div>
</div>

app/views/admin/products/index.html.erb
<h1>Listing products</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.status.humanize %></td>
        <td>
          <%= link_to 'Show', admin_product_path(product) %>
          <%= link_to 'Edit', edit_admin_product_path(product) %>
          <%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path, class: 'btn btn-default' %>

app/views/admin/products/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>New product</h1>
		<%= render 'form', submit_text: "Create" %>
		<%= link_to 'Back', products_path, class: 'btn btn-default' %>		
	</div>
</div>

app/views/admin/products/search.html.erb
<h1>Search for <%= params[:query] %></h1>
<ul>
<% @products.each do |p| %>
	<li>
		<p><%= p.name %></p>
		<p><%= p.description %></p>
	</li>
<% end %>
</ul>

app/views/admin/products/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
	<% @product.pictures.each do |pic| %>
		<%= image_tag pic.image.url(:medium) %>
	<% end %>
	<p>
	  <strong>Name:</strong>
	  <%= @product.name %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @product.description %>
	</p>
	<p>
	  <strong>Status:</strong>
	  <%= @product.status.humanize %>
	</p>
	<% if logged_in? %>
		<% if policy(@product).edit? %>
			<%= link_to 'Edit', edit_admin_product_path(@product), class: 'btn btn-default' %> |
			<%= link_to 'Back', admin_products_path, class: 'btn btn-default' %>
		<% end %>
	<% end %>
	</div>
</div>