config/routes.rb
Rails.application.routes.draw do
  resources :password_resets

  namespace :admin do
  get 'dashboard/index'
  end

  get 'sessions/new'

  resources :products, only: [:index, :show]

  root "static_pages#home"

  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  get 'logout' => "sessions#destroy"
  get 'home' => "static_pages#home"
  get 'about' => "static_pages#about"
  get 'contact' => "static_pages#contact"

  get 'search' => "products#search"

  namespace :admin do
    get '' => "dashboard#index", as: '/'
    resources :products
    resources :users
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	enum role: %w(user admin)
	has_secure_password

	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, length: { maximum: 200 },
										uniqueness: { case_sensitive: true },
										format: { with: EMAIL_REGEX }
	validates :password, presence: true, length: { minimum: 6 }, if: :password

	before_save { self.email = email.downcase }
	before_create { generate_token(:auth_token) }

	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent_at = Time.zone.now
		save!
		UserMailer.password_reset(self).deliver
	end


	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists? column => self[column]
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  after_action :verify_authorized
  #before_action :require_permission, only: [:edit, :update, :destroy]
  #before_action :authorize_user, only: [:new, :create, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    authorize @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize @user
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    authorize @user
    respond_to do |format|
      if @user.save
        flash[:success] = 'User was successfully created.' 
        format.html { redirect_to [:admin, @user] }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize @user
    respond_to do |format|
      if params[:role] && !current_user.admin?
        flash[:warning] = 'You do not have permission to change user\'s role'
        render :edit 
      elsif current_user.admin? && @user.update(user_params)
        flash[:success] = 'User was successfully updated.'
        format.html { redirect_to [:admin, @user] }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
    end

    def require_permission
      @user = User.find(params[:id])
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "You don't have permission to modify this user's."
        redirect_to(request.referrer || root_url)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  after_action :verify_authorized
  #before_action :require_permission, only: [:edit, :update, :destroy]
  #before_action :authorize_user, only: [:new, :create, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    authorize @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize @user
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    authorize @user
    respond_to do |format|
      if @user.save
        flash[:success] = 'User was successfully created.' 
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = 'User was successfully updated.'
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
    end

    def require_permission
      @user = User.find(params[:id])
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "You don't have permission to modify this user's."
        redirect_to(request.referrer || root_url)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user], html: {class: 'inner-form'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>This form contains <%= pluralize(@user.errors.count, "error") %></h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <% if current_user.admin? %>
    <div class="field">
      <%= f.label :role %>
      <%= f.select :role, User.roles.collect {|r, v| [r.humanize, r]}, {}, {class: 'form-control'} %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit submit_text, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<h1>Editing user</h1>

		<%= render 'form', submit_text: "Save changes" %>

		<%= link_to 'Show', admin_user_path(@user) %> |
		<%= link_to 'Back', admin_users_path %>
	</div>
</div>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', admin_user_path(user) %>
        <% if current_user?(user) || current_user.admin? %>
          <%= link_to 'Edit', edit_admin_user_path(user) %>
        <% end %>
        <% if current_user.admin? %>
          <%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path, class: 'btn btn-default' %>

app/views/admin/users/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>New user</h1>

		<%= render 'form', submit_text: "Create user" %>

		<%= link_to 'Back', admin_users_path %>
	</div>
</div>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>