config/routes.rb
Rails.application.routes.draw do
  resources :password_resets

  namespace :admin do
  get 'dashboard/index'
  end

  get 'sessions/new'

  resources :products, only: [:index, :show]

  root "static_pages#home"

  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  get 'logout' => "sessions#destroy"
  get 'home' => "static_pages#home"
  get 'about' => "static_pages#about"
  get 'contact' => "static_pages#contact"

  get 'search' => "products#search"

  namespace :admin do
    get '' => "dashboard#index", as: '/'
    resources :products
    resources :users
  end

end

app/views/layouts/_header.html.erb
<header class="header">
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "Sample Store", root_path, class: 'navbar-brand' %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	      	<%= form_tag search_path, method: :get, enforce_utf8: false, class: 'navbar-form navbar-left', role: 'search' do %>
	      		<div class="form-group">
	      			<%= text_field_tag :query, params[:query], class: 'form-control', placeholder: "Type here..." %>
	      		</div>
	      			<%= submit_tag "Search", name: nil, class:'btn btn-default' %>
	      	<% end %>
	        <!--<form class="navbar-form navbar-left" role="search">
		        <div class="form-group">
		          <input type="text" class="form-control" placeholder="Type here...">
		        </div>
		        <button type="submit" class="btn btn-default">Search</button>
		      </form>-->
	        <li class="<%= current_page('about', controller) %>"><a href="<%= about_path %>">About</a></li>
	        <li class="<%= current_page('contact', controller) %>"><a href="<%= contact_path %>">Contact</a></li>
	        <% if logged_in? %>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Welcome, <%= current_user.name %> <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><%= link_to "Profile", admin_user_path(current_user) %></li>
	            <li><%= link_to "Settings", edit_admin_user_path(current_user) %></li>
	            <% if policy(Product).index? %>
		          	<li><%= link_to "Products", admin_products_path %></li>
		          <% end %>
		          <% if policy(User).index? %>
		          	<li><%= link_to "Users", admin_users_path %></li>
		          <% end %>
	            <li class="divider"></li>
	            <li><%= link_to "Log out", logout_path %></li>
	          </ul>
	        </li>
	        <% else %>
	        <li><a href="#">#</a></li>
	       	<% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |type, message| %>
		<div class="alert alert-<%= type %>"><%= message %></div>
	<% end %>
	<%= yield %>
</div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>